#!/usr/bin/env python3


import argparse

from lib import ebeinput
from lib import stats


def main():
    parser = argparse.ArgumentParser(description='''Calculate Kullback–Leibler
            divergence between generalized gamma distributions.  Intended to
            compare many approximate distributions to a single true
            distribution.''')

    parser.add_argument('p0', nargs=4, type=float,
        help='True gengamma parameters (a,c,loc,scale).')

    parser.add_argument('files', nargs='*', help='''File[s] to process.  Omit or
            use '-' to read from stdin.  Each line should contain approximate
            (a,c,loc,scale).''')

    args = parser.parse_args()


    for l in ebeinput.lines(args.files):
        p = tuple(map(float,l.split()))
        print(stats.gengamma_kl(p,args.p0))


if __name__ == "__main__":
    main()
