#!/usr/bin/env python3


import argparse

from lib.ebeinput import events_from_files


parser = argparse.ArgumentParser(description='''Read UrQMD files and output standard
        particle info.  Optionally filter particles with the following arguments.''')
parser.add_argument('files', nargs='*', help='''Files to read.  Omit or use '-'
        to read from stdin.''')
parser.add_argument('-i', '--input', metavar='auto|std|urqmd', choices=['auto','std','urqmd'],
        default='auto', help='Input format, default:  auto.')
parser.add_argument('--ID', type=int, nargs='+',
        help='Particle IDs, space separated.')
parser.add_argument('--charged', action='store_true',
        help='Shortcut for all charged particles.')
parser.add_argument('--pTmin', type=float, help='pT minimum.')
parser.add_argument('--pTmax', type=float, help='pT maximum.')
parser.add_argument('--etamin', type=float, help='eta minimum; if no etamax, \
        equivalent to etamin < |eta|.')
parser.add_argument('--etamax', type=float, help='eta maximum; if no etamin, \
        equivalent to |eta| < etamax.')
args = parser.parse_args()


# convert the args Namespace to a dictionary
argdict = vars(args)

# pop the list of files and input format
# argdict now holds only the particle filtering options
files = argdict.pop('files')
inputformat = argdict.pop('input')


def main():
    for e in events_from_files(files=files,inputformat=inputformat,**argdict):
        for p in e:
            print(*p)
        print()


if __name__ == "__main__":
    main()
