#!/usr/bin/env python3

import argparse
import fileinput
from functions import read_events


parser = argparse.ArgumentParser(description='''Read event files and output standard
        particle info.''')
parser.add_argument('files', nargs='*', help='''Files to read.  Omit or use '-'
        to read from stdin.''')
args = parser.parse_args()


def main():
    with fileinput.input(files=args.files,openhook=fileinput.hook_compressed) as f:
        for l in read_events(f):
            print(*l)


if __name__ == "__main__":
    main()
