#!/usr/bin/env python3

import fileinput
from lib import urqmd


def main():
    with fileinput.input(openhook=fileinput.hook_compressed) as f:
        urqmd.tostdout(f)


if __name__ == "__main__":
    main()
