#!/usr/bin/env python3


from lib.parse import EbEParser
from lib.ebeinput import events_from_files


def main():
    parser = EbEParser(
        description='Calculate event multiplicities.')

    args = parser.parse_args()

    for e in events_from_files(**vars(args)):
        print(len(e))


if __name__ == "__main__":
    main()
